apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniboard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniboard
  template:
    metadata:
      labels:
        app: miniboard
    spec:
      containers:
      - name: miniboard
        image: docker.io/redleon1/miniboard_miniboard:{{VERSION}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-secret

---
apiVersion: v1
kind: Service
metadata:
  name: miniboard-service
spec:
  ports:
  - port: 8080
    nodePort: 30002
  selector:
    app: miniboard
  type: NodePort
